api_platform:
    show_webby: false
    # formats:
    #     json: ['application/json']
    title: "Chat Legal Pilot"
    version: 0.0.1
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
